In [5]:
# LCM-8

import numpy as np
noAlloc = 0
inf = np.iinfo(np.int32).max

# input of rows and columns
r = int(input("Enter the number of Rows: "))
c = int(input("\nEnter the number of Columns:"))

# building the cost matrix
print("\nEnter the entries in a single line (separated by space): \n")
entries = list(map(int, input().split()))
cm = np.array(entries).reshape(r, c)
print("\nCost Matrix")
print(cm)

# building the supply matrix
print("\nRows, Columns: (",r,",",c,")")
print("\nEnter Supply values: ")
s = list(map(int, input().split()))
print("\nSupply Matrix: ")
print(s)

# building the demand matrix
print("\nEnter Demand values: ")
d = list(map(int, input().split()))
print("\nDemand Matrix: ",sep = '')
print(d)

# calculating total demand and supply
total_demand = np.sum(d)
total_supply = np.sum(s)

# checking if the problem is balanced
if total_demand == total_supply:
    print("\nThis is a Balanced Transportation Problem.")
else:
    print("\nThis is an Unbalanced Transportation Problem")

# for balanching the problem if unbalanced
if total_demand < total_supply:
    cm = np.insert(cm, c-1, 0, axis = 1)
    cm[r-1][c-1] = total_supply - total_demand
    c += 1
else:
    cm = np.insert(cm, r-1, 0, axis = 0)
    cm[r-1][c-1] = total_demand - total_supply
    r += 1

print()
i=0
j=0
A = np.zeros([r, c], dtype=int)
min_cost = np.amin(costMatrix)

# loop for allocation by LCM
while min_cost != inf and i<r and j<c:
    indices = np.where(cm == min_cost)
    i = indices[0][0]
    j = indices[1][0]
    x = min(s[i],d[j])
    s[i] -= x
    d[j] -= x
    noAlloc += 1
    A[i][j] = x

    if s[i] < d[j]:
        j = 0
        while j < c:
            cm[i][j] = inf
            j += 1
    elif s[i] > d[j]:
        i = 0
        while i < r:
            cm[i][j] = inf
            i += 1
    else:
        k = 0
        while k < c:
            cm[i][k] = inf
            k += 1
        k = 0
        while k < r:
            cm[k][j] = inf
            k += 1
        min_cost = np.amin(costMatrix)

print("\nNo of Allocation: ", noAlloc)
print("\nThe Allocation Matrix:\n")
print(A)

if (r + c - 1) == noAlloc and total_demand == total_supply:
    print("\nIt is not a Degenerate Solution")
else:
    print("\nDegenerate Solution")

Enter the number of Rows: 3

Enter the number of Columns:4

Enter the entries in a single line (separated by space): 

5 4 2 6 8 3 5 7 5 2 4 6

Cost Matrix
[[5 4 2 6]
 [8 3 5 7]
 [5 2 4 6]]

Rows, Columns: ( 3 , 4 )

Enter Supply values: 
20 30 50

Supply Matrix: 
[20, 30, 50]

Enter Demand values: 
10 40 20 30

Demand Matrix: 
[10, 40, 20, 30]

This is a Balanced Transportation Problem.

No of Allocation:  1

The Allocation Matrix:

[[ 0  0  0  0]
 [ 0  0  0  0]
 [10  0  0  0]
 [ 0  0  0  0]]

Degenerate Solution


In [6]:
 # LCM-8

import numpy as np
noAlloc = 0
inf = np.iinfo(np.int32).max

# input of rows and columns
r = int(input("Enter the number of Rows: "))
c = int(input("\nEnter the number of Columns:"))

# building the cost matrix
print("\nEnter the entries in a single line (separated by space): \n")
entries = list(map(int, input().split()))
cm = np.array(entries).reshape(r, c)
print("\nCost Matrix")
print(cm)

# building the supply matrix
print("\nRows, Columns: (",r,",",c,")")
print("\nEnter Supply values: ")
s = list(map(int, input().split()))
print("\nSupply Matrix: ")
print(s)

# building the demand matrix
print("\nEnter Demand values: ")
d = list(map(int, input().split()))
print("\nDemand Matrix: ",sep = '')
print(d)

# calculating total demand and supply
total_demand = np.sum(d)
total_supply = np.sum(s)

# checking if the problem is balanced
if total_demand == total_supply:
    print("\nThis is a Balanced Transportation Problem.")
else:
    print("\nThis is an Unbalanced Transportation Problem")

# for balanching the problem if unbalanced
if total_demand < total_supply:
    cm = np.insert(cm, c-1, 0, axis = 1)
    cm[r-1][c-1] = total_supply - total_demand
    c += 1
else:
    cm = np.insert(cm, r-1, 0, axis = 0)
    cm[r-1][c-1] = total_demand - total_supply
    r += 1

print()
i=0
j=0
A = np.zeros([r, c], dtype=int)
min_cost = np.amin(costMatrix)

# loop for allocation by LCM
while min_cost != inf and i<r and j<c:
    indices = np.where(cm == min_cost)
    i = indices[0][0]
    j = indices[1][0]
    x = min(s[i],d[j])
    s[i] -= x
    d[j] -= x
    noAlloc += 1
    A[i][j] = x

    if s[i] < d[j]:
        j = 0
        while j < c:
            cm[i][j] = inf
            j += 1
    elif s[i] > d[j]:
        i = 0
        while i < r:
            cm[i][j] = inf
            i += 1
    else:
        k = 0
        while k < c:
            cm[i][k] = inf
            k += 1
        k = 0
        while k < r:
            cm[k][j] = inf
            k += 1
        min_cost = np.amin(costMatrix)

print("\nNo of Allocation: ", noAlloc)
print("\nThe Allocation Matrix:\n")
print(A)

if (r + c - 1) == noAlloc and total_demand == total_supply:
    print("\nIt is not a Degenerate Solution")
else:
    print("\nDegenerate Solution")

Enter the number of Rows: 3

Enter the number of Columns:4

Enter the entries in a single line (separated by space): 

5 4 2 6 8 3 5 7 5 2 4 6

Cost Matrix
[[5 4 2 6]
 [8 3 5 7]
 [5 2 4 6]]

Rows, Columns: ( 3 , 4 )

Enter Supply values: 
20 30 50

Supply Matrix: 
[20, 30, 50]

Enter Demand values: 
10 40 20 30

Demand Matrix: 
[10, 40, 20, 30]

This is a Balanced Transportation Problem.


No of Allocation:  1

The Allocation Matrix:

[[ 0  0  0  0]
 [ 0  0  0  0]
 [10  0  0  0]
 [ 0  0  0  0]]

Degenerate Solution
